/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceConfig A device configuration.
type DeviceConfig struct {
	// The ID of the device.
	DeviceId string `json:"deviceId,omitempty"`
	// The component ID on the device.
	ComponentId string `json:"componentId,omitempty"`
}
