/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceSettingAllOf struct for DeviceSettingAllOf
type DeviceSettingAllOf struct {
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// Indicates if this device setting can have multiple values.
	Multiple bool `json:"multiple,omitempty"`
	// Indicates if this input should close on selection.
	CloseOnSelection bool `json:"closeOnSelection,omitempty"`
	// Indicates if this input should refresh configs after a change in value.
	SubmitOnChange bool `json:"submitOnChange,omitempty"`
	// Indicates if the first device in the list of options should be pre selected.
	Preselect bool `json:"preselect,omitempty"`
	// The required capabilities for the device(s) options.
	Capabilities []string `json:"capabilities,omitempty"`
	// The excluded capabilities for the device(s) options.
	ExcludeCapabilities []string `json:"excludeCapabilities,omitempty"`
	// The required permissions for the selected device(s).
	Permissions []string `json:"permissions,omitempty"`
	Style StyleType `json:"style,omitempty"`
}
