/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// MessageConfig A message configuration.
type MessageConfig struct {
	// The key value of the message group.
	MessageGroupKey string `json:"messageGroupKey,omitempty"`
}
