/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// OAuthSettingAllOf struct for OAuthSettingAllOf
type OAuthSettingAllOf struct {
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// The url to use for the OAuth service. Use __SmartThingsOAuthCallback__ in the template for the callback/redirect url you need to provide to the OAuth service. 
	UrlTemplate string `json:"urlTemplate,omitempty"`
	Style StyleType `json:"style,omitempty"`
}
