/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ExecutionResponse Expected response structure for an SmartApp execution.  An execution response is compositional in nature.  Client's should set exactly one *Data field depending on the type of execution.  For example, if the execution request's lifecycle was of type EVENT, the \"eventData\" field should be returned. 
type ExecutionResponse struct {
	StatusCode int32 `json:"statusCode,omitempty"`
	// Empty object response for an Event lifecycle execution. 
	EventData map[string]interface{} `json:"eventData,omitempty"`
	// Empty object response for an Install lifecycle execution. 
	InstallData map[string]interface{} `json:"installData,omitempty"`
	// Empty object response for an Update lifecycle execution. 
	UpdateData map[string]interface{} `json:"updateData,omitempty"`
	// Empty object response for an Uninstall lifecycle execution. 
	UninstallData map[string]interface{} `json:"uninstallData,omitempty"`
	ConfigurationData ConfigurationResponseData `json:"configurationData,omitempty"`
	PingData PingResponseData `json:"pingData,omitempty"`
	// Empty object response for an OAuth Callback lifecycle execution. 
	OauthCallbackData map[string]interface{} `json:"oauthCallbackData,omitempty"`
	// A custom JSON formatted response object with a maximum size of 64kb. 
	ExecuteData map[string]interface{} `json:"executeData,omitempty"`
	DashboardData DashboardResponseData `json:"dashboardData,omitempty"`
}
