/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// EventType The type of event passed to the app being executed. The type will be one of:   * DEVICE_COMMANDS_EVENT - _Only applicable for cloud-to-cloud device integration apps._ An event as a result of a device command execution request.   * DEVICE_EVENT - A device event as a result of a subscription the app created.   * DEVICE_HEALTH_EVENT - A device health event as a result of a change in a device's health.   * DEVICE_LIFECYCLE_EVENT - A device lifecycle event as the result of a life change to the device.   * MODE_EVENT - A mode event is triggered when the location's mode is changed.   * SCENE_LIFECYCLE_EVENT - A scene lifecycle event as a result of a life change to the scene.   * SECURITY_ARM_STATE_EVENT - A security arm state event as a result of a change in the arm state of a security system.   * TIMER_EVENT - An event as a result of a scheduled app execution. 
type EventType string

// List of EventType
const (
	EVENTTYPE_DEVICE_COMMANDS_EVENT EventType = "DEVICE_COMMANDS_EVENT"
	EVENTTYPE_DEVICE_EVENT EventType = "DEVICE_EVENT"
	EVENTTYPE_DEVICE_HEALTH_EVENT EventType = "DEVICE_HEALTH_EVENT"
	EVENTTYPE_DEVICE_LIFECYCLE_EVENT EventType = "DEVICE_LIFECYCLE_EVENT"
	EVENTTYPE_MODE_EVENT EventType = "MODE_EVENT"
	EVENTTYPE_SCENE_LIFECYCLE_EVENT EventType = "SCENE_LIFECYCLE_EVENT"
	EVENTTYPE_SECURITY_ARM_STATE_EVENT EventType = "SECURITY_ARM_STATE_EVENT"
	EVENTTYPE_TIMER_EVENT EventType = "TIMER_EVENT"
)
