/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicV2Button A button definition for a Basic V2 template.
type BasicV2Button struct {
	Type BasicButtonType `json:"type,omitempty"`
	TextButton BasicV2TextButton `json:"textButton,omitempty"`
	IconButton BasicV2IconButton `json:"iconButton,omitempty"`
}
