/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// InitializeSettingAllOf struct for InitializeSettingAllOf
type InitializeSettingAllOf struct {
	// A developer defined page ID of the first page to display. Must be URL safe characters.
	FirstPageId string `json:"firstPageId,omitempty"`
	// Disable the ability for the user to customize the display name.
	DisableCustomDisplayName bool `json:"disableCustomDisplayName,omitempty"`
	// Disable the ability to remove the app from the configuration flow.
	DisableRemoveApp bool `json:"disableRemoveApp,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}
