/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// SettingType Denotes the type of setting.
type SettingType string

// List of SettingType
const (
	SETTINGTYPE_DEVICE SettingType = "DEVICE"
	SETTINGTYPE_DATE SettingType = "DATE"
	SETTINGTYPE_TEXT SettingType = "TEXT"
	SETTINGTYPE_PASSWORD SettingType = "PASSWORD"
	SETTINGTYPE_BOOLEAN SettingType = "BOOLEAN"
	SETTINGTYPE_ENUM SettingType = "ENUM"
	SETTINGTYPE_MODE SettingType = "MODE"
	SETTINGTYPE_SCENE SettingType = "SCENE"
	SETTINGTYPE_LINK SettingType = "LINK"
	SETTINGTYPE_PAGE SettingType = "PAGE"
	SETTINGTYPE_IMAGE SettingType = "IMAGE"
	SETTINGTYPE_IMAGES SettingType = "IMAGES"
	SETTINGTYPE_VIDEO SettingType = "VIDEO"
	SETTINGTYPE_TIME SettingType = "TIME"
	SETTINGTYPE_PARAGRAPH SettingType = "PARAGRAPH"
	SETTINGTYPE_EMAIL SettingType = "EMAIL"
	SETTINGTYPE_DECIMAL SettingType = "DECIMAL"
	SETTINGTYPE_NUMBER SettingType = "NUMBER"
	SETTINGTYPE_PHONE SettingType = "PHONE"
	SETTINGTYPE_OAUTH SettingType = "OAUTH"
	SETTINGTYPE_SOUND SettingType = "SOUND"
	SETTINGTYPE_COLOR SettingType = "COLOR"
	SETTINGTYPE_MESSAGE_GROUP SettingType = "MESSAGE_GROUP"
)
