/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// PageSettingAllOf struct for PageSettingAllOf
type PageSettingAllOf struct {
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// The page to navigate to.
	Page string `json:"page,omitempty"`
	// The image url.
	Image string `json:"image,omitempty"`
	Style LinkStyleType `json:"style,omitempty"`
}
