/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// SceneSettingAllOf struct for SceneSettingAllOf
type SceneSettingAllOf struct {
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// Indicates if this scene setting can have multiple values.
	Multiple bool `json:"multiple,omitempty"`
	// Indicates if this input should close on selection.
	CloseOnSelection bool `json:"closeOnSelection,omitempty"`
	// Indicates if this input should refresh configs after a change in value.
	SubmitOnChange bool `json:"submitOnChange,omitempty"`
	Style StyleType `json:"style,omitempty"`
}
