/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ExecuteAction Call the EXECUTE lifecycle on the backing SmartApp.
type ExecuteAction struct {
	// An arbitrary map of input parameters which the SmartApp can use to build a custom response.
	Parameters map[string]string `json:"parameters,omitempty"`
}
