/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// PingResponseData Expected response for a Ping lifecycle execution. 
type PingResponseData struct {
	// An echo of the challenge that was provided on the request.
	Challenge string `json:"challenge,omitempty"`
}
