/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicButtonType The type of buttons to render.  * TEXT - A colored button with a text overrlay. * ICON - A button with an image backgroup and text overrlay. 
type BasicButtonType string

// List of BasicButtonType
const (
	BASICBUTTONTYPE_TEXT BasicButtonType = "TEXT"
	BASICBUTTONTYPE_ICON BasicButtonType = "ICON"
)
