/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ConfigurationData A request for a pages flow to drive app installation.  This will only be available for executions of type \"CONFIGURATION\". 
type ConfigurationData struct {
	// The id of the installed app.
	InstalledAppId string `json:"installedAppId,omitempty"`
	Phase ConfigurationPhase `json:"phase"`
	// A developer defined page ID. Must be URL safe characters.
	PageId string `json:"pageId,omitempty"`
	// The previous page the user completed. Must be URL safe characters.
	PreviousPageId string `json:"previousPageId,omitempty"`
	// A map of configurations for an Installed App.  The map 'key' is the configuration name and the 'value' is an array of strings. 
	Config map[string][]ConfigEntry `json:"config,omitempty"`
}
