/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
import (
	"time"
)
// TimerEvent An event that is caused by a schedule for this app being fired.
type TimerEvent struct {
	// The ID of the event.
	EventId string `json:"eventId,omitempty"`
	// The name of the schedule that caused this event.
	Name string `json:"name,omitempty"`
	Type TimerType `json:"type,omitempty"`
	// The IS0-8601 date time strings in UTC that this event was scheduled for.
	Time time.Time `json:"time,omitempty"`
	// The CRON expression if the schedule was of type CRON.
	Expression string `json:"expression,omitempty"`
}
