/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// LinkStyleType Style of the setting.
type LinkStyleType string

// List of LinkStyleType
const (
	LINKSTYLETYPE_COMPLETE LinkStyleType = "COMPLETE"
	LINKSTYLETYPE_ERROR LinkStyleType = "ERROR"
	LINKSTYLETYPE_DEFAULT LinkStyleType = "DEFAULT"
	LINKSTYLETYPE_BUTTON LinkStyleType = "BUTTON"
)
