/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceLifecycle The device lifecycle. The lifecycle will be one of: * CREATE - Invoked when a device is created. * DELETE - Invoked when a device is deleted. * UPDATE - Invoked when a device is updated. * MOVE_FROM - Invoked when a device is moved from a location. * MOVE_TO - Invoked when a device is moved to a location. 
type DeviceLifecycle string

// List of DeviceLifecycle
const (
	DEVICELIFECYCLE_CREATE DeviceLifecycle = "CREATE"
	DEVICELIFECYCLE_DELETE DeviceLifecycle = "DELETE"
	DEVICELIFECYCLE_UPDATE DeviceLifecycle = "UPDATE"
	DEVICELIFECYCLE_MOVE_FROM DeviceLifecycle = "MOVE_FROM"
	DEVICELIFECYCLE_MOVE_TO DeviceLifecycle = "MOVE_TO"
)
