/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicCard Data requirements for a Basic V1 card template.
type BasicCard struct {
	// name of the card
	Name string `json:"name,omitempty"`
	// A title icon url for card. Angit  HTTPS URL is required.
	IconUrl string `json:"iconUrl,omitempty"`
	BgImage BasicBackgroundImage `json:"bgImage,omitempty"`
	Body BasicBody `json:"body,omitempty"`
	// A list of buttons to render and buttons must be of the same type.
	Buttons []BasicButton `json:"buttons,omitempty"`
}
