/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicButton A button definition for a Basic V1 template.
type BasicButton struct {
	Type BasicButtonType `json:"type,omitempty"`
	TextButton BasicTextButton `json:"textButton,omitempty"`
	IconButton BasicIconButton `json:"iconButton,omitempty"`
}
