/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// AppLifecycle Every invocation of a SmartApp is associated to a specific lifecycle event.  These lifecycles include: * INSTALL - Lifecycle that will be invoked once at the time of installation of a SmartApp. * UPDATE - Invoked when a user modifies the configuration values assigned to the SmartApp. * UNINSTALL - A clean up lifecycle invoked upon the deletion of an SmartApp from a user's account. * EVENT - Lifecycle event used when the SmartApp is invoked as the result of a subscription or schedule. * PING - Lifecycle used during App creation to verify connectivity, and ownership of a particular target. * CONFIGURATION - Lifecycle used to drive the UX during the installation process of a SmartApp into a user's account. * OAUTH_CALLBACK - Lifecycle used for integrations that implement a third-party OAuth out. * CONFIRMATION - Lifecycle used to send confirmation link to a SmartApp for ownership validation. 
type AppLifecycle string

// List of AppLifecycle
const (
	APPLIFECYCLE_INSTALL AppLifecycle = "INSTALL"
	APPLIFECYCLE_UPDATE AppLifecycle = "UPDATE"
	APPLIFECYCLE_UNINSTALL AppLifecycle = "UNINSTALL"
	APPLIFECYCLE_EVENT AppLifecycle = "EVENT"
	APPLIFECYCLE_PING AppLifecycle = "PING"
	APPLIFECYCLE_CONFIGURATION AppLifecycle = "CONFIGURATION"
	APPLIFECYCLE_OAUTH_CALLBACK AppLifecycle = "OAUTH_CALLBACK"
	APPLIFECYCLE_CONFIRMATION AppLifecycle = "CONFIRMATION"
)
