/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// SimpleValue A simple value.
type SimpleValue struct {
	// The type of the value. 
	ValueType string `json:"valueType,omitempty"`
	IntValue int32 `json:"intValue,omitempty"`
	DoubleValue float64 `json:"doubleValue,omitempty"`
	StringValue string `json:"stringValue,omitempty"`
	BoolValue bool `json:"boolValue,omitempty"`
}
