/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ExecutionRequest The root model for all executions.  An execution request is compositional in nature.  Client's can expect exactly one *Data field set depending on the type of execution.  For example, if execution is of type EVENT, the \"eventData\" field will be set. 
type ExecutionRequest struct {
	Lifecycle AppLifecycle `json:"lifecycle,omitempty"`
	// This is a correlation id that is assigned to the execution that is useful for support requests.
	ExecutionId string `json:"executionId,omitempty"`
	// A globally unique identifier for the application being executed. It should match the ID of the application itself.
	AppId string `json:"appId,omitempty"`
	// An IETF BCP 47 language tag representing the chosen locale for this account.
	Locale string `json:"locale,omitempty"`
	// The version of the execution's request model.
	Version string `json:"version,omitempty"`
	Client ClientDetails `json:"client,omitempty"`
	EventData EventData `json:"eventData,omitempty"`
	InstallData InstallData `json:"installData,omitempty"`
	UpdateData UpdateData `json:"updateData,omitempty"`
	UninstallData UninstallData `json:"uninstallData,omitempty"`
	ConfigurationData ConfigurationData `json:"configurationData,omitempty"`
	PingData PingData `json:"pingData,omitempty"`
	OauthCallbackData OAuthCallbackData `json:"oauthCallbackData,omitempty"`
	ExecuteData ExecuteData `json:"executeData,omitempty"`
	DashboardData DashboardData `json:"dashboardData,omitempty"`
	ConfirmationData ConfirmationData `json:"confirmationData,omitempty"`
	// Global settings as defined on the App.
	Settings map[string]string `json:"settings,omitempty"`
}
