/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// VideoSettingAllOf struct for VideoSettingAllOf
type VideoSettingAllOf struct {
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// The video url.
	Video string `json:"video,omitempty"`
	// The image url.
	Image string `json:"image,omitempty"`
}
