/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// OAuthSetting OAuth Setting
type OAuthSetting struct {
	// A developer defined configuration ID.
	Id string `json:"id,omitempty"`
	// Name of the setting to be configured.
	Name string `json:"name,omitempty"`
	// Description of the app to be configured.
	Description string `json:"description,omitempty"`
	// Indicates if this setting is required for configuration.
	Required bool `json:"required,omitempty"`
	// Indicates if this setting should be disabled
	Disabled bool `json:"disabled,omitempty"`
	Type SettingType `json:"type"`
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// The url to use for the OAuth service. Use __SmartThingsOAuthCallback__ in the template for the callback/redirect url you need to provide to the OAuth service. 
	UrlTemplate string `json:"urlTemplate,omitempty"`
	Style StyleType `json:"style,omitempty"`
}
