/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceCommandsEvent An event that contains commands for devices that were created by this app.
type DeviceCommandsEvent struct {
	// The id of the event.
	EventId string `json:"eventId,omitempty"`
	// The guid of the device that the commands are for.
	DeviceId string `json:"deviceId,omitempty"`
	// The device profile ID of the device instance.
	ProfileId string `json:"profileId,omitempty"`
	// The external ID that was set during install of a device.
	ExternalId string `json:"externalId,omitempty"`
	Commands []DeviceCommandsEventCommand `json:"commands,omitempty"`
}
