/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DashboardResponseData Expected response for a Dashboard lifecycle execution. 
type DashboardResponseData struct {
	// A unique identifier for a card of service
	ServiceName string `json:"serviceName,omitempty"`
	// list of card object
	Cards []DashboardCard `json:"cards,omitempty"`
}
