/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicV2Item Item in Basic V2 items
type BasicV2Item struct {
	Item BasicV2ImageItem `json:"item,omitempty"`
}
