/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DashboardData The data payload to an execution request with an AppLifecycle of DASHBOARD.
type DashboardData struct {
	// An OAuth token to use when calling into SmartThings API's.
	AuthToken string `json:"authToken"`
	InstalledApp InstalledApp `json:"installedApp"`
}
