/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DashboardCardTemplate A directive to the SmartThings client to use a specific template for rendering the dashboard card. Each card template may have a different set requirement for data needs.  * BASIC_V1 - The basic / default template. * FREE_FORM - A free form template with minimal constraints. 
type DashboardCardTemplate string

// List of DashboardCardTemplate
const (
	DASHBOARDCARDTEMPLATE_BASIC_V1 DashboardCardTemplate = "BASIC_V1"
	DASHBOARDCARDTEMPLATE_BASIC_V2 DashboardCardTemplate = "BASIC_V2"
	DASHBOARDCARDTEMPLATE_FREE_FORM DashboardCardTemplate = "FREE_FORM"
)
