/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// TimerType The type of TIMER_EVENT.
type TimerType string

// List of TimerType
const (
	TIMERTYPE_CRON TimerType = "CRON"
	TIMERTYPE_ONCE TimerType = "ONCE"
)
