/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// Option struct for Option
type Option struct {
	// The unique ID for this option.
	Id string `json:"id,omitempty"`
	// The display name for this option.
	Name string `json:"name,omitempty"`
}
