/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicV2IconButton A text button definition for a basic V2 template.
type BasicV2IconButton struct {
	// The name of the button
	Name string `json:"name,omitempty"`
	// An icon image url on button-released. HTTPS url required.
	ReleasedIconUrl string `json:"releasedIconUrl,omitempty"`
	// An icon image url on button-pressed. HTTPS url required.
	PressedIconUrl string `json:"pressedIconUrl,omitempty"`
	Action Action `json:"action,omitempty"`
}
