/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ModeConfig A mode configuration.
type ModeConfig struct {
	// The ID of the mode.
	ModeId string `json:"modeId,omitempty"`
}
