/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// SceneLifecycleEvent A scene lifecycle event.
type SceneLifecycleEvent struct {
	Lifecycle SceneLifecycle `json:"lifecycle,omitempty"`
	// The id of the event.
	EventId string `json:"eventId,omitempty"`
	// The id of the location in which the event was triggered.
	LocationId string `json:"locationId,omitempty"`
	// The id of the scene.
	SceneId string `json:"sceneId,omitempty"`
	// Create scene lifecycle. 
	Create map[string]interface{} `json:"create,omitempty"`
	// Update scene lifecycle. 
	Update map[string]interface{} `json:"update,omitempty"`
	// Delete scene lifecycle. 
	Delete map[string]interface{} `json:"delete,omitempty"`
}
