/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceLifecycleMove Move device lifecycle. 
type DeviceLifecycleMove struct {
	LocationId string `json:"locationId,omitempty"`
}
