/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceEvent An event on a device that matched a subscription for this app.
type DeviceEvent struct {
	// The ID of the event.
	EventId string `json:"eventId,omitempty"`
	// The ID of the location in which the event was triggered.
	LocationId string `json:"locationId,omitempty"`
	// The ID of the device associated with the DEVICE_EVENT.
	DeviceId string `json:"deviceId,omitempty"`
	// The name of the component on the device that the event is associated with.
	ComponentId string `json:"componentId,omitempty"`
	// The name of the capability associated with the DEVICE_EVENT.
	Capability string `json:"capability,omitempty"`
	// The name of the DEVICE_EVENT. This typically corresponds to an attribute name of the device-handler’s capabilities.
	Attribute string `json:"attribute,omitempty"`
	// The value of the event. The type of the value is dependent on the capability's attribute type. 
	Value map[string]interface{} `json:"value,omitempty"`
	// The root level data type of the value field. The data types are representitive of standard JSON data types. 
	ValueType string `json:"valueType,omitempty"`
	// Whether or not the state of the device has changed as a result of the DEVICE_EVENT.
	StateChange bool `json:"stateChange,omitempty"`
	// json map as defined by capability data schema
	Data map[string]interface{} `json:"data,omitempty"`
	// The name of subscription that caused delivery.
	SubscriptionName string `json:"subscriptionName,omitempty"`
}
