/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceHealthEvent An event that represents a change in the health of the a device.
type DeviceHealthEvent struct {
	// The id of the event.
	EventId string `json:"eventId,omitempty"`
	// The id of the location in which the event was triggered.
	LocationId string `json:"locationId,omitempty"`
	// The id of the device.
	DeviceId string `json:"deviceId,omitempty"`
	// The id of the hub.
	HubId string `json:"hubId,omitempty"`
	// The status of the device. 
	Status string `json:"status,omitempty"`
	// The reason the device is offline. 
	Reason string `json:"reason,omitempty"`
}
