/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicImage struct for BasicImage
type BasicImage struct {
	// An icon name.
	Name string `json:"name,omitempty"`
	Position BasicImagePosition `json:"position,omitempty"`
	// URL of image.  HTTPS url is required.
	Url string `json:"url,omitempty"`
}
