/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// StyleType Style of the setting.
type StyleType string

// List of StyleType
const (
	STYLETYPE_COMPLETE StyleType = "COMPLETE"
	STYLETYPE_ERROR StyleType = "ERROR"
	STYLETYPE_DEFAULT StyleType = "DEFAULT"
)
