/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicV2Text A text object.
type BasicV2Text struct {
	// Text to display.
	Content string `json:"content,omitempty"`
	Action Action `json:"action,omitempty"`
}
