/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// TextSetting Text Setting
type TextSetting struct {
	// A developer defined configuration ID.
	Id string `json:"id,omitempty"`
	// Name of the setting to be configured.
	Name string `json:"name,omitempty"`
	// Description of the app to be configured.
	Description string `json:"description,omitempty"`
	// Indicates if this setting is required for configuration.
	Required bool `json:"required,omitempty"`
	// Indicates if this setting should be disabled
	Disabled bool `json:"disabled,omitempty"`
	Type SettingType `json:"type"`
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// The maximum length the text can have.
	MaxLength int32 `json:"maxLength,omitempty"`
	// The minimum length the text can have.
	MinLength int32 `json:"minLength,omitempty"`
	// The image url.
	Image string `json:"image,omitempty"`
	// A string to be shown after the text input field.
	PostMessage string `json:"postMessage,omitempty"`
}
