/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// InstalledApp The information associated with this installed app.
type InstalledApp struct {
	// The id of the installed app.
	InstalledAppId string `json:"installedAppId,omitempty"`
	// The location that the installed App is associated with
	LocationId string `json:"locationId,omitempty"`
	// A map of configurations for an Installed App.  The map 'key' is the configuration name and the 'value' is an array of strings. 
	Config map[string][]ConfigEntry `json:"config,omitempty"`
	// A list of permissions associated with this execution. See `securityDefinitions` for more information.
	Permissions []string `json:"permissions,omitempty"`
}
