/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ConfigurationPhase Denotes the current installation phase.
type ConfigurationPhase string

// List of ConfigurationPhase
const (
	CONFIGURATIONPHASE_INITIALIZE ConfigurationPhase = "INITIALIZE"
	CONFIGURATIONPHASE_PAGE ConfigurationPhase = "PAGE"
)
