/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicButtonPosition Position of where the button should be rendered within card.
type BasicButtonPosition string

// List of BasicButtonPosition
const (
	BASICBUTTONPOSITION_LEFT BasicButtonPosition = "LEFT"
	BASICBUTTONPOSITION_CENTER BasicButtonPosition = "CENTER"
	BASICBUTTONPOSITION_RIGHT BasicButtonPosition = "RIGHT"
)
