/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ClientDetails Known details about the client application from which the request was initiated.  This information is provided on best effort basis.  All properties maybe null or empty. 
type ClientDetails struct {
	// The operating system of the client application initiating the request.
	Os string `json:"os,omitempty"`
	// The version of the client application initiating the request.
	Version string `json:"version,omitempty"`
	// Language header representing the client's preferred language. The format of the `Accept-Language` header follows what is defined in [RFC 7231, section 5.3.5](https://tools.ietf.org/html/rfc7231#section-5.3.5)
	Language string `json:"language,omitempty"`
	// Templates that could be renderable in the client
	SupportedTemplates []string `json:"supportedTemplates,omitempty"`
}
