/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceCommandsEventCommand struct for DeviceCommandsEventCommand
type DeviceCommandsEventCommand struct {
	ComponentId string `json:"componentId,omitempty"`
	Capability string `json:"capability,omitempty"`
	Command string `json:"command,omitempty"`
	Arguments []map[string]interface{} `json:"arguments,omitempty"`
}
