/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// DeviceSetting Device Setting
type DeviceSetting struct {
	// A developer defined configuration ID.
	Id string `json:"id,omitempty"`
	// Name of the setting to be configured.
	Name string `json:"name,omitempty"`
	// Description of the app to be configured.
	Description string `json:"description,omitempty"`
	// Indicates if this setting is required for configuration.
	Required bool `json:"required,omitempty"`
	// Indicates if this setting should be disabled
	Disabled bool `json:"disabled,omitempty"`
	Type SettingType `json:"type"`
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// Indicates if this device setting can have multiple values.
	Multiple bool `json:"multiple,omitempty"`
	// Indicates if this input should close on selection.
	CloseOnSelection bool `json:"closeOnSelection,omitempty"`
	// Indicates if this input should refresh configs after a change in value.
	SubmitOnChange bool `json:"submitOnChange,omitempty"`
	// Indicates if the first device in the list of options should be pre selected.
	Preselect bool `json:"preselect,omitempty"`
	// The required capabilities for the device(s) options.
	Capabilities []string `json:"capabilities,omitempty"`
	// The excluded capabilities for the device(s) options.
	ExcludeCapabilities []string `json:"excludeCapabilities,omitempty"`
	// The required permissions for the selected device(s).
	Permissions []string `json:"permissions,omitempty"`
	Style StyleType `json:"style,omitempty"`
}
func (DeviceSetting) isSectionSetting() {}
