/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// EnumStyleType Style of the setting.
type EnumStyleType string

// List of EnumStyleType
const (
	ENUMSTYLETYPE_COMPLETE EnumStyleType = "COMPLETE"
	ENUMSTYLETYPE_ERROR EnumStyleType = "ERROR"
	ENUMSTYLETYPE_DEFAULT EnumStyleType = "DEFAULT"
	ENUMSTYLETYPE_DROPDOWN EnumStyleType = "DROPDOWN"
)
