/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ConfigEntry A configuration value type and the correspodning configuration.
type ConfigEntry struct {
	// The value type. * A valueType of STRING will have a stringConfig field present. * A valueType of DEVICE will have a deviceConfig field present. * A valueType of MODE will have a modeConfig field present. * A valueType of SCENE will have a sceneConfig field present. * A valueType of MESSAGE will have a messageConfig field present. 
	ValueType string `json:"valueType,omitempty"`
	StringConfig StringConfig `json:"stringConfig,omitempty"`
	DeviceConfig DeviceConfig `json:"deviceConfig,omitempty"`
	ModeConfig ModeConfig `json:"modeConfig,omitempty"`
	SceneConfig SceneConfig `json:"sceneConfig,omitempty"`
	MessageConfig MessageConfig `json:"messageConfig,omitempty"`
}
