/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// ConfigurationResponseData Expected response for a Configuration lifecycle execution.  ConfigurationResponseData follows a compositional structure. * When a request is made for the INITIALIZE phase, a InitializeInstall model should be returned. * When a request is made for the PAGE phase, a Page model should be returned. 
type ConfigurationResponseData struct {
	Initialize InitializeSetting `json:"initialize,omitempty"`
	Page Page `json:"page,omitempty"`
}
