/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicV2Body Body definition for a Basic V2 template.
type BasicV2Body struct {
	Image BasicV2Image `json:"image,omitempty"`
	// Body item array definition for a Basic V2 template
	Items []BasicV2Item `json:"items,omitempty"`
	Text BasicV2Text `json:"text,omitempty"`
}
