/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
import (
	"time"
)
// Event The event information, only populated if the execution type is EVENT.
type Event struct {
	// The IS0-8601 date time string in UTC that this event was created.
	EventTime time.Time `json:"eventTime,omitempty"`
	EventType EventType `json:"eventType,omitempty"`
	DeviceEvent DeviceEvent `json:"deviceEvent,omitempty"`
	DeviceLifecycleEvent DeviceLifecycleEvent `json:"deviceLifecycleEvent,omitempty"`
	DeviceHealthEvent DeviceHealthEvent `json:"deviceHealthEvent,omitempty"`
	DeviceCommandsEvent DeviceCommandsEvent `json:"deviceCommandsEvent,omitempty"`
	ModeEvent ModeEvent `json:"modeEvent,omitempty"`
	TimerEvent TimerEvent `json:"timerEvent,omitempty"`
	SceneLifecycleEvent SceneLifecycleEvent `json:"sceneLifecycleEvent,omitempty"`
	SecurityArmStateEvent SecurityArmStateEvent `json:"securityArmStateEvent,omitempty"`
}
