/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// SecurityArmStateEvent An event that represents a change in the arm state of a security system. 
type SecurityArmStateEvent struct {
	// The id of the event.
	EventId string `json:"eventId,omitempty"`
	// The id of the location in which the event was triggered.
	LocationId string `json:"locationId,omitempty"`
	// The arm state of a security system. 
	ArmState string `json:"armState,omitempty"`
	// A set of key / value pairs useful for passing any optional arguments. 
	OptionalArguments map[string]SimpleValue `json:"optionalArguments,omitempty"`
}
