/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// LaunchPluginAction Launch a backing UI plugin in SmartThings Client.
type LaunchPluginAction struct {
	// The ID of the plugin to launch.
	PluginId string `json:"pluginId,omitempty"`
	// parameter to be passed to plugin
	Uri string `json:"uri,omitempty"`
}
