/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// SceneLifecycle The scene lifecycle. The lifecycle will be one of: * CREATE - Invoked when a scene is created. * UPDATE - Invoked when a scene is updated. * DELETE - Invoked when a scene is deleted. 
type SceneLifecycle string

// List of SceneLifecycle
const (
	SCENELIFECYCLE_CREATE SceneLifecycle = "CREATE"
	SCENELIFECYCLE_UPDATE SceneLifecycle = "UPDATE"
	SCENELIFECYCLE_DELETE SceneLifecycle = "DELETE"
)
