/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicBody Body definition for a Basic V1 template.
type BasicBody struct {
	Image BasicImage `json:"image,omitempty"`
	Text BasicText `json:"text,omitempty"`
}
