/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicImagePosition Position of where the image should be rendered within card.
type BasicImagePosition string

// List of BasicImagePosition
const (
	BASICIMAGEPOSITION_LEFT BasicImagePosition = "LEFT"
	BASICIMAGEPOSITION_CENTER BasicImagePosition = "CENTER"
	BASICIMAGEPOSITION_RIGHT BasicImagePosition = "RIGHT"
)
