/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// BasicV2Image struct for BasicV2Image
type BasicV2Image struct {
	Position BasicImagePosition `json:"position,omitempty"`
	// URL of image.  HTTPS url is required.
	Url string `json:"url,omitempty"`
	Action Action `json:"action,omitempty"`
}
