/*
 * SmartThings SmartApps API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smartapp
// TextSettingAllOf struct for TextSettingAllOf
type TextSettingAllOf struct {
	// A default value for the setting.
	DefaultValue string `json:"defaultValue,omitempty"`
	// The maximum length the text can have.
	MaxLength int32 `json:"maxLength,omitempty"`
	// The minimum length the text can have.
	MinLength int32 `json:"minLength,omitempty"`
	// The image url.
	Image string `json:"image,omitempty"`
	// A string to be shown after the text input field.
	PostMessage string `json:"postMessage,omitempty"`
}
